### ISSUE TITLE
The impact of different feature extractors

### ISSUE THREAD

**Issue by FischLu** [vislearn/ngransac#13]
Hello,

I am trying to train a model by myself. The training data set mentioned in the repository includes feature correspondence for sift, orb, rootsift. I have checked them in detail, which only include coordinates of matched features and side information. No descriptor information included and needed. So in such case, how much of a difference it makes for using different training data? Does a model trained on SIFT data work well to match ORB feature?? Thank you.

**Comment by ebrach** [comment]
Hi,

I found it to generalise rather well, for example from SIFT to ORB. It depends on whether you expect the distribution of feature coordinates to be very different from what the pre-trained models were trained on (PhotoTourims data, and indoor office footage). For example, if your data has a very different (unusual) aspect ratio, your feature detector responds to different structures that SIFT (eg. blobs instead of corners), or you find many more or much less matches that SIFT - than I would expect that re-training would make sense.

Let me know what you find, if you investigate further in this direction :) 

Best,
Eric

**Comment by FischLu** [comment]
Thanks for response, I tried to use models which are trained on SIFT and ORB to match features from LIFT, which doesn't work as good as SIFT or ORB. I am planning to retrain the model for LIFT, so I will update if I get something.
