### ISSUE TITLE
How to calculate the gradient of  log p(H;w) about the parameter w?

### ISSUE THREAD

**Issue by DRjy** [vislearn/ngransac#14]
By reading the source code of ngransac,  I found that the calculation of   
![image](https://user-images.githubusercontent.com/46476977/121990047-b8f63680-cdcf-11eb-99b9-1c23dc3e57f5.png)

is the number of  times of each element of correspondence is picked at random. Can you explain the theory behind the calculation in detail?  Because it is hard for me to draw the conclusion.  Thank you in advance! @ebrach

**Comment by ebrach** [comment]
Hi,

sorry for the delay! Always happy to answer questions about the theory :) 

The network predicts log probabilities, and the gradients that we calculate are with respect to the output of the network. That means in the equation above, we do not differentiate wrt to w (network parameters) but wrt log p. The derivative of log p wrt log p is 1. That is why we have a one for any correspondence that has been picked. If it was picked multiple times, we sum those 1s up. 

The remaining differentiation (log p wrt w) is handled by the deep learning framework.

Best,
Eric

**Comment by DRjy** [comment]
Thanks for your kind reply very much. Now, I think I may understand some parts as follows: According to the chain rule, we can derive the following equation :
![image](https://user-images.githubusercontent.com/46476977/123800316-c2c58100-d91b-11eb-9a03-a9d75f0827b4.png)

In resource code, we calculate the value of  ：
![image](https://user-images.githubusercontent.com/46476977/123800371-cf49d980-d91b-11eb-814d-e4ad3088ec55.png)

For the value of  ![image](https://user-images.githubusercontent.com/46476977/123800454-e688c700-d91b-11eb-90c5-2ef5951d279f.png)
, is there a detailed derivation ?  or how to explain it in theory? Intuitively, for some correspondence picked up, the value is one, and sum up those 1 if the same correspondence sampled by many times. But I feel I can not get it thoroughly.
Thank you again!

**Comment by ebrach** [comment]
<img width="1212" alt="Screenshot 2021-07-05 at 14 45 20" src="https://user-images.githubusercontent.com/17846386/124473494-b1f39000-dd9f-11eb-9118-8ccb89fe0ca1.png">

I hope my scribbles are useful ;( According to Eq. 2 of the paper, we can decompose the log probability of an hypothesis pool p(H) into the sum of probabilities for picking individual data points log p(y_i) that constitute the models minimal set . This is what the network predicts. For F/E matrix fitting, one datapoint is one image correspondence, and the network predicts one sampling weight.

Then, we go to Eq. 5, and instead of deriving it wrt the network parameters w, we derive it wrt log p(y_i), i.e. wrt the log probabilities of each individual data point. We substitute p(H) by the sums of p(y_i) according to Eq. 2. 

What happens now is the following:
a) p(y_i) derived wrt to p(y_i) is one 
b) but only if it is actually part of the hypothesis in the pool

That is why we assemble gradients by counting the correspondences we sample according to the prediction of the network.

**Comment by DRjy** [comment]
Thank you very much for your kindly and detailed interpretation. I have understand it thoroughly. Thank you again!
