### ISSUE TITLE
Unable to replicate demo

### ISSUE THREAD

**Issue by ayushbaid** [vislearn/ngransac#2]
Hi,
I am trying to replicate the demo using the following command: python ngransac_demo.py -img1 images/demo1.jpg -fl1 900 -img2 images/demo2.jpg -fl2 900.

I am running the code on a machine without a GPU (and hence made a couple of changes in the demo code to run on cpu. The demo does not work for me as described.

My runtime: Linux x64 (Ubuntu 19.04)
Python version: 3.7.4
Running in a conda env with Pytorch and OpenCv installed.

This is the image
![demo](https://user-images.githubusercontent.com/3755532/65471288-a211f280-de3c-11e9-809a-0f51282d63ed.png)

**Comment by ebrach** [comment]
Hi, 
RANSAC and NG-RANSAC are randomized algorithms, hence it is hard to tell from a single example whether your alterations changed the behavior of NG-RANSAC or not. I can replicate your results if I let NG-RANSAC sample longer. 

I would recommend a quantitative test to verify that NG-RANSAC still performs as it should. If you download our data package you can run 

python ngransac_test.py -ds reichstag
and you should get something like:
"AUC for 5deg/10deg/20deg: 0.42/0.54/0.62"

python ngransac_test.py -ds sacre_coeur
and you should get something like:
"AUC for 5deg/10deg/20deg: 0.52/0.56/0.61"

Make sure to pull the latest version since I just fixed a bug in the test script. 

Results for reichstag might vary a bit, since they are computed on 52 image pairs only.
Results for sacre_coeur should be stable, but take longer to compute.
