### ISSUE TITLE
using other features extractor than the default ones

### ISSUE THREAD

**Issue by arielbenitah** [vislearn/ngransac#3]
Hi, 

it's not really an issue but a question: Is it possible to run it with a feature extractor which is different from the default ones (ORB, SIFT, ROOTSIFT)? 
I'd like to use as feature extractor: SURF, AKAZE or HAHOG.

Is it possible to use one of the pre-trained models with those features extractor?

thanks a lot.

Ariel

**Comment by ebrach** [comment]
Yes, absolutely. For example, you could substitute the SIFT constructor in the demo script with any other feature extractor. Since the OpenCV interfaces are very similar, there should not need to adapt much else. The pre-trained models should also work fairly well. I would start by loading a SIFT model (and since you have overwritten the SIFT constructor, you will automatically load a SIFT model by default).

Let me know how that works out.

Best,
Eric

**Comment by arielbenitah** [comment]
Hi, thanks a lot for your answer. I'm currently doing exactly as you suggest... I'll update you as I progress...
Thanks for your help.

Ariel
