### ISSUE TITLE
gcc version

### ISSUE THREAD

**Issue by Theodoric008** [vislearn/ngransac#7]
when I do " python setup.py install "
i got error: "  undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
"

i guess it is something about gcc version, can u help me? thx!

**Comment by ebrach** [comment]
Hi,

I'm not exactly sure what is causing that error, but since it is pointing to caffe, my best guess that it is not related to NG-RANSAC itself, but to your local PyTorch installation. The C++ linker seems to have problems finding the Caffe2 library (or parts of it) which is part of PyTorch. 

Have you tried compiling other C++ extensions? E.g. following this tutorial: https://pytorch.org/tutorials/advanced/cpp_extension.html

In any case: We currently use GCC 7.3.0 if that is of any help.

Best,
Eric

**Comment by Theodoric008** [comment]
Hi:
Thanks for replying! I will follow your suggestion and try! Thanks!

**Comment by Theodoric008** [comment]
Great! Problem Solved!
1.  I should fill in opencv header and lib path in ./ngransac/setup.py 
2. import torch before import ngransac !!
Thanks a lot !

Theodoric008
